version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - service-data:/var/lib/postgresql/data
      # copy the sql script to create db & table
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
volumes:
  service-data:
    driver: local
